### ISSUE TITLE
Broken link to DadaGen UI

### ISSUE THREAD

**Issue by sammythehat** [inosion/dadagen#14]
Hey @rbuckland,

Did you know the link to download DadaGen UI in [DadagenUI.md](https://github.com/inosion/dadagen/blob/master/docs/DadagenUI.md) is giving a 404?

[This one](https://bintray.com/artifact/download/inosion/maven/org/inosion/dadagen/dadagen-ui/dadagen-ui-0.2.9.jar).

Sam

**Comment by rbuckland** [comment]
Thanks Sammy - that has been resolved.
